name: docker-compose
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build stack
        run: docker-compose up -d
      
      - name: Curl client
        run:  curl -I http://localhost:3000/
      
      - name: Curl api
        run: |
         curl -i http://localhost:5000/api/appointments
         sleep 5
         curl -I -X GET http://localhost:5000/api/timeslots
