name: docker-compose
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build stack
        run: |
         docker-compose up -d
         docker-compose build
      - name: Test client
        run: appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
      - name: Test server appointments
        run: appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/api/appointments
