name: docker-compose
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build stack
        run: docker-compose up -d
      - name: Test client
        run: docker run --network container:client appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
      - name: Test server
        run: docker run --network container:server appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
