name: docker-compose
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build stack
        run: |
         docker-compose up -d
         docker-compose build
         
      - name: curl client
        uses: wei/curl@master
        with:
         args: http://localhost:3000/
